domain: "pavillion.dev"

# Example mail configurations - uncomment and adjust as needed
# mail:
#   transport: smtp
#   from: noreply@pavillion.dev
#   settings:
#     host: smtp.example.com
#     port: 587
#     secure: false
#     user: youruser
#     pass: yourpassword

# Development configuration - writes emails to files
mail:
  transport: development
  from: noreply@pavillion.dev
  settings:
    outputDir: logs/mail
    console: true

media:
  uploadPath: './storage/media/inbound'
  finalPath: './storage/media/public'
  maxFileSize: 10485760  # 10MB in bytes
  allowedTypes:
    - 'image/png'
    - 'image/jpeg'
    - 'image/heic'
  allowedExtensions:
    - '.png'
    - '.jpg'
    - '.jpeg'
    - '.heic'
